[package]
name = "mikomai"
version = "0.1.0"
description = "Managed Infrastructure Knowledge Operator of Ml Agent Interface."
authors = ["NAKAOKU Takahiro"]
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "mikomai_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
llama-cpp-2 = "0.1.146"
lancedb = "0.27.2"
fastembed = "4"
arrow = "57"
arrow-array = "57"
arrow-json = "57"
hf-hub = "0.5.0"
tokio = { version = "1.52.1", features = ["full"] }
futures = "0.3.32"
tauri-plugin-shell = "2.3.5"
surge-ping = "0.8.4"
mcp-core = "0.1.50"
mcp-server = "0.1.0"
mcp-client = "0.1.0"
chrono = "0.4.44"
uuid = { version = "1.23.1", features = ["v4"] }
tokio-cron-scheduler = "0.15.1"
tauri-plugin-dialog = "2.7.1"
serialport = "4.7.0"
dns-lookup = "3.0.1"
regex = "1.12.3"

