use serde::Serialize;
use std::collections::HashMap;

pub const DEVICE_TYPES: &[&str] = &[
    "a10",
    "accedian",
    "adtran_os",
    "adva_fsp150f2",
    "adva_fsp150f3",
    "alaxala_ax36s",
    "alaxala_ax26s",
    "alcatel_aos",
    "alcatel_sros",
    "allied_telesis_awplus",
    "apc_aos",
    "apresia_aeos",
    "arista_eos",
    "arris_cer",
    "aruba_os",
    "aruba_aoscx",
    "aruba_osswitch",
    "aruba_procurve",
    "asterfusion_asternos",
    "audiocode_72",
    "audiocode_66",
    "audiocode_shell",
    "avaya_ers",
    "avaya_vsp",
    "avara_aos",
    "aviat_wtm",
    "bintec_boss",
    "broadcom_icos",
    "brocade_fos",
    "brocade_fastiron",
    "brocade_netiron",
    "brocade_nos",
    "brocade_vdx",
    "brocade_vyos",
    "checkpoint_gaia",
    "calix_b6",
    "calix_exa",
    "casa_cmts",
    "cdot_cros",
    "centec_os",
    "ciena_saos",
    "ciena_saos10",
    "ciena_waveserver",
    "cisco_ap",
    "cisco_apic",
    "cisco_asa",
    "cisco_ftd",
    "cisco_ios",
    "cisco_nxos",
    "cisco_s200",
    "cisco_s300",
    "cisco_s500",
    "cisco_tp",
    "cisco_viptela",
    "cisco_wlc",
    "cisco_ioswlc",
    "cisco_xe",
    "cisco_xr",
    "cloudgenix_ion",
    "corelight_linux",
    "coriant",
    "cumulus_linux",
    "dell_dnos9",
    "dell_force10",
    "dell_os6",
    "dell_os9",
    "dell_os10",
    "dell_sonic",
    "dell_powerconnect",
    "dell_isilon",
    "dlink_ds",
    "digi_transport",
    "edgecore_sonic",
    "endace",
    "ekinops_ek360",
    "eltex",
    "eltex_esr",
    "enterasys",
    "ericsson_ipos",
    "ericsson_mltn63",
    "ericsson_mltn66",
    "extreme",
    "extreme_ers",
    "extreme_exos",
    "extreme_netiron",
    "extreme_nos",
    "extreme_slx",
    "extreme_tierra",
    "extreme_vdx",
    "extreme_vsp",
    "extreme_wing",
    "f5_ltm",
    "f5_tmsh",
    "f5_linux",
    "fiberstore_fsos",
    "fiberstore_fsosv2",
    "fiberstore_networkos",
    "flexvnf",
    "fortinet",
    "fsas_sir",
    "fujitsu_sir",
    "furukawa_fitelnet",
    "garderos_grs",
    "generic",
    "generic_termserver",
    "h3c_comware",
    "hillstone_stoneos",
    "hirschmann_hios",
    "hp_comware",
    "hp_procurve",
    "huawei",
    "huawei_smartaxmmi",
    "huawei_smartax",
    "huawei_olt",
    "huawei_ont",
    "huawei_vrp",
    "huawei_vrpv8",
    "infinera_packet",
    "ipinfusion_ocnos",
    "juniper",
    "juniper_junos",
    "juniper_screenos",
    "keymile",
    "keymile_nos",
    "lancom_lcossx4",
    "lancom_lcossx5",
    "linux",
    "mikrotik_routeros",
    "mikrotik_switchos",
    "mellanox",
    "mellanox_mlnxos",
    "moxa_nos",
    "mrv_lx",
    "mrv_optiswitch",
    "nec_ix",
    "netapp_cdot",
    "netgear_prosafe",
    "netscaler",
    "nokia_isam",
    "nokia_sros",
    "nokia_srl",
    "oneaccess_oneos",
    "opengear_linux",
    "ovs_linux",
    "paloalto_panos",
    "pluribus",
    "perle_iolan",
    "quanta_mesh",
    "rad_etx",
    "raisecom_roap",
    "raisecom_ros",
    "ruckus_fastiron",
    "ruijie_os",
    "iij_seilos",
    "silverpeak_vxoa",
    "sixwind_os",
    "smartoptics_dwdm",
    "sophos_fos",
    "supermicro_smis",
    "telcosystems_binos",
    "teldat_cit",
    "tplink_jetstream",
    "ubiquiti_edge",
    "ubiquiti_edgerouter",
    "ubiquiti_edgeswitch",
    "ubiquiti_unifiswitch",
    "vertiv_mph",
    "vyatta_vyos",
    "vyos",
    "watchguard_fireware",
    "zpe_nodegrid",
    "zte_zxros",
    "yamaha",
    "zyxel_os",
    "maipu",
];

pub const DEVICE_TYPE_ALIASES: &[(&str, &str)] = &[
    ("a10", "A10 Networks"),
    ("accedian", "Accedian"),
    ("adtran_os", "Adtran OS"),
    ("alaxala_ax36s", "ALAXALA AX36S"),
    ("alaxala_ax26s", "ALAXALA AX26S"),
    ("alcatel_aos", "Alcatel-Lucent AOS"),
    ("alcatel_sros", "Alcatel-Lucent SROS"),
    ("allied_telesis_awplus", "Allied Telesis AlliedWare Plus"),
    ("apc_aos", "APC AOS"),
    ("apresia_aeos", "APRESIA AEOS"),
    ("arista_eos", "Arista EOS"),
    ("arris_cer", "Arris CER"),
    ("aruba_os", "ArubaOS"),
    ("aruba_aoscx", "ArubaOS-CX"),
    ("aruba_osswitch", "ArubaOS-Switch"),
    ("aruba_procurve", "Aruba ProCurve"),
    ("cisco_ios", "Cisco IOS"),
    ("cisco_nxos", "Cisco NX-OS"),
    ("cisco_xe", "Cisco IOS-XE"),
    ("cisco_xr", "Cisco IOS-XR"),
    ("cisco_asa", "Cisco ASA"),
    ("cisco_ftd", "Cisco FTD"),
    ("cisco_wlc", "Cisco WLC"),
    ("cisco_apic", "Cisco APIC"),
    ("dell_os6", "Dell OS6"),
    ("dell_os9", "Dell OS9"),
    ("dell_os10", "Dell OS10"),
    ("dell_sonic", "Dell Enterprise SONiC"),
    ("extreme_exos", "Extreme EXOS"),
    ("fortinet", "Fortinet FortiOS"),
    ("h3c_comware", "H3C Comware"),
    ("hp_comware", "HP Comware"),
    ("hp_procurve", "HP ProCurve"),
    ("huawei", "Huawei VRP"),
    ("huawei_vrpv8", "Huawei VRPv8"),
    ("iij_seilos", "IIJ SEIL/OS"),
    ("juniper_junos", "Juniper Junos"),
    ("linux", "Linux"),
    ("mikrotik_routeros", "MikroTik RouterOS"),
    ("mikrotik_switchos", "MikroTik SwitchOS"),
    ("nec_ix", "NEC UNIVERGE IX"),
    ("nokia_sros", "Nokia SR OS"),
    ("nokia_srl", "Nokia SR Linux"),
    ("paloalto_panos", "Palo Alto PAN-OS"),
    ("ruckus_fastiron", "Ruckus FastIron"),
    ("ruijie_os", "Ruijie RGOS"),
    ("yamaha", "Yamaha RT"),
    ("zte_zxros", "ZTE ZXROS"),
    ("zyxel_os", "ZyXEL ZyNOS"),
];

#[derive(Serialize, Clone, Debug)]
#[serde(rename_all = "camelCase")]
pub struct DeviceTypesResponse {
    pub device_types: &'static [&'static str],
    pub device_type_aliases: HashMap<&'static str, &'static str>,
}

#[tauri::command]
pub fn get_device_types() -> DeviceTypesResponse {
    let mut aliases = HashMap::new();
    for &(key, val) in DEVICE_TYPE_ALIASES {
        aliases.insert(key, val);
    }
    DeviceTypesResponse {
        device_types: DEVICE_TYPES,
        device_type_aliases: aliases,
    }
}
