#!/usr/bin/env python3
"""Generate native GraphDB DDL from router-resources.json (no YANG dependency)."""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "crates/mikomai-adapters/src/schema"
resources = json.loads((SCHEMA / "router-resources.json").read_text())
lines = ["-- Generated by scripts/generate-router-schema.py; edit router-resources.json."]
for resource in resources:
    table = resource["table"]
    assert re.fullmatch(r"[a-z_]+", table)
    lines += [f"\n-- {resource['yang_file']} ({resource['yang_revision']})",
              f"DEFINE TABLE IF NOT EXISTS {table} SCHEMAFULL;"]
    for field in ["key", "device_name", "observation_id", "observed_at"]:
        lines.append(f"DEFINE FIELD IF NOT EXISTS {field} ON TABLE {table} TYPE string;")
    for field in resource["fields"]:
        name, base = field["name"], field["type"]
        assert re.fullmatch(r"[a-z][a-z0-9_]*", name)
        assert base in ["string", "int", "float", "bool", "object", "array<object>", "array<string>", "array<int>"]
        typ = base if field["required"] else f"option<{base}>"
        flexible = " FLEXIBLE" if "object" in base else ""
        allowed = field.get("allowed", [])
        bounds = []
        if "minimum" in field:
            bounds.append(f"$value >= {field['minimum']}")
        if "maximum" in field:
            bounds.append(f"$value <= {field['maximum']}")
        condition = f"$value IN {json.dumps(allowed)}" if allowed else " AND ".join(bounds)
        if not condition and base == "int":
            condition = "$value >= 0"
        if not condition and base == "string" and field["required"]:
            condition = "string::trim($value) != ''"
        assertion = ""
        if condition:
            assertion = f" ASSERT ({condition})" if field["required"] else f" ASSERT $value = NONE OR ({condition})"
        lines.append(f"DEFINE FIELD IF NOT EXISTS {name} ON TABLE {table} TYPE {typ}{flexible}{assertion};")
    identity = ", ".join(["device_name"] + resource["identity"])
    lines += [f"DEFINE INDEX IF NOT EXISTS resource_identity ON TABLE {table} FIELDS {identity} UNIQUE;",
              f"DEFINE INDEX IF NOT EXISTS resource_device_time ON TABLE {table} FIELDS device_name, observed_at;"]
output = "\n".join(lines) + "\n"
target = SCHEMA / "router-schema.surql"
if "--check" in sys.argv:
    if not target.exists() or target.read_text() != output:
        raise SystemExit("router-schema.surql is out of date")
else:
    target.write_text(output)
