# ==============================================================================
# Netmiko ベンダー別 デフォルトコマンドテンプレート定義ファイル
# ==============================================================================

cisco_ios:
  fetch_config: "show running-config"
  fetch_route: "show ip route"
  fetch_bgp: "show ip bgp summary"
  fetch_arp: "show ip arp"

juniper_junos:
  fetch_config: "show configuration"
  fetch_route: "show route"
  fetch_bgp: "show bgp summary"
  fetch_arp: "show arp"

arista_eos:
  fetch_config: "show running-config"
  fetch_route: "show ip route"
  fetch_bgp: "show ip bgp summary"
  fetch_arp: "show ip arp"

yamaha:
  fetch_config: "show config"
  fetch_route: "show ip route"
  fetch_bgp: "show ip bgp summary"
  fetch_arp: "show arp"

furukawa_fitelnet:
  fetch_config: "show running-config"
  fetch_route: "show ip route"
  fetch_bgp: "show ip bgp summary"
  fetch_arp: "show ip arp"
