/** Backend command names shared by feature facades. */
export const COMMANDS = {
  chat: "handle_mcp_message",
  loadSettings: "load_settings",
  saveSettings: "save_settings",
  loadConnections: "load_connections",
  mcpHosts: "get_mcp_hosts",
  resolveIp: "resolve_ip",
  startTask: "start_task",
  resumeTask: "resume_task",
  submitUserChoice: "submit_user_choice",
  createOperationPlan: "create_operation_plan",
  approveOperationPlan: "approve_operation_plan",
  executeOperationPlan: "execute_approved_operation_plan",
  stopLlm: "stop_llm",
  resumeAgentTask: "resume_agent_task",
  submitInterfaceChoice: "submit_interface_choice",
  submitIpAddressChoice: "submit_ipaddress_choice",
  createNetworkConfigOperationPlan: "create_network_config_operation_plan",
  openModelDir: "open_model_dir",
  openPathInFileManager: "open_path_in_file_manager",
  copyFileToDestination: "copy_file_to_destination",
  prepareAttachments: "prepare_attachments",
  exportConnections: "export_connections_csv",
  deviceTypes: "get_device_types",
  saveConnections: "save_connections",
  getWatches: "list_watches",
  updateWatch: "update_watch",
  createWatch: "create_watch",
  enableWatch: "enable_watch",
  disableWatch: "disable_watch",
  executeWatchNow: "execute_watch_now",
  deleteWatch: "delete_watch",
  checkModelExists: "check_model_exists",
  downloadModel: "download_model",
  loadModel: "load_model",
  listSerialPorts: "network_list_serial_ports",
  refreshNodeDb: "start_node_db_bulk_refresh",
  listAgentTasks: "list_agent_tasks",
  getAgentTaskAudit: "get_agent_task_audit",
  importConnections: "import_connections_csv",
  getModelStatus: "get_model_status",
  getLoadedModelPath: "get_loaded_model_path",
  loadSummaries: "load_summaries",
  mutateHistory: "mutate_history",
  initializeHistory: "initialize_history",
} as const;

export type CommandName = typeof COMMANDS[keyof typeof COMMANDS];

export const EVENTS = {
  chat: "chat-event",
  diffRequested: "request-diff-commit",
  commitStatus: "commit-status",
  modelStatus: "model-status-changed",
  dragOver: "tauri://drag-over",
  dragLeave: "tauri://drag-leave",
  dragDrop: "tauri://drag-drop",
  fileDrop: "tauri://file-drop",
  watchExecuted: "watch-executed",
  keyringAccessStart: "keyring-access-start",
  keyringAccessEnd: "keyring-access-end",
  requestUserChoice: "request-user-choice",
  requestInterfaceChoice: "request-interface-choice",
  requestIpAddressChoice: "request-ipaddress-choice",
  commitLog: "commit-log",
  requestForceCommit: "request-force-commit",
  commitDiffResult: "commit-diff-result",
  watchNotification: "watch-notification",
  modelLoaded: "model-loaded",
} as const;

export type EventName = typeof EVENTS[keyof typeof EVENTS];
