import Foundation
public struct MikomaiResult { public let status: Int32; public let message: UnsafeMutablePointer<CChar>? }
public typealias MikomaiStreamCallback = (UnsafePointer<CChar>?, Int32, UnsafeMutableRawPointer?) -> Void
public typealias MikomaiToolCallback = (UnsafePointer<CChar>?, UnsafePointer<CChar>?, UnsafePointer<CChar>?, UnsafeMutablePointer<CChar>?, UInt, UnsafeMutableRawPointer?) -> Int32
public typealias MikomaiPlanCallback = (UnsafePointer<CChar>?, UnsafePointer<CChar>?, UnsafePointer<CChar>?, UnsafePointer<CChar>?, UnsafeMutablePointer<CChar>?, UInt, UnsafeMutableRawPointer?) -> Int32
public typealias MikomaiWatchNotificationCallback = (UnsafePointer<CChar>?, UnsafeMutableRawPointer?) -> Void
public typealias MikomaiOperationCompletionCallback = (Int32, UnsafePointer<CChar>?, UnsafeMutableRawPointer?) -> Void
private final class CompatListener: LegacyListener, @unchecked Sendable {
let stream: MikomaiStreamCallback?; let notice: MikomaiWatchNotificationCallback?; let context: UnsafeMutableRawPointer?
init(_ stream: MikomaiStreamCallback?, _ notice: MikomaiWatchNotificationCallback?, _ context: UnsafeMutableRawPointer?) { self.stream=stream; self.notice=notice; self.context=context }
func event(kind:String,text:String,done:Bool) { text.withCString { p in if kind == "notification" { notice?(p,context) } else { stream?(p,done ? 1:0,context) } } }
}
public func mikomai_result_free(_ value:MikomaiResult) { free(value.message) }
private func invoke(_ op:String,_ args:[String],_ listener: LegacyListener? = nil)->MikomaiResult { let result=legacyInvoke(op:op,args:args,listener:listener); return MikomaiResult(status:result.status,message:strdup(result.text)) }
public func mikomai_dispatch_mode(_ message: UnsafePointer<CChar>?,_ devices_json: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_dispatch_mode",[message.map { String(cString:$0) } ?? "",devices_json.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_agent_chat_streaming(_ message: UnsafePointer<CChar>?,_ history: UnsafePointer<CChar>?,_ documents_dir: UnsafePointer<CChar>?,_ knowledge_dir: UnsafePointer<CChar>?,_ attachments: UnsafePointer<CChar>?,_ devices_json: UnsafePointer<CChar>?,_ callback: MikomaiStreamCallback?,_ tool_callback: MikomaiToolCallback?,_ plan_callback: MikomaiPlanCallback?,_ context: UnsafeMutableRawPointer?)->MikomaiResult { invoke("mikomai_agent_chat_streaming",[message.map { String(cString:$0) } ?? "",history.map { String(cString:$0) } ?? "",documents_dir.map { String(cString:$0) } ?? "",knowledge_dir.map { String(cString:$0) } ?? "",attachments.map { String(cString:$0) } ?? "",devices_json.map { String(cString:$0) } ?? ""],CompatListener(callback,nil,context)) }
public func mikomai_agent_task_list()->MikomaiResult { invoke("mikomai_agent_task_list",[],nil) }
public func mikomai_agent_task_history(_ id: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_agent_task_history",[id.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_agent_task_delete(_ id: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_agent_task_delete",[id.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_agent_task_delete_all()->MikomaiResult { invoke("mikomai_agent_task_delete_all",[],nil) }
public func mikomai_watch_start(_ storage_path: UnsafePointer<CChar>?,_ tool_callback: MikomaiToolCallback?,_ notification_callback: MikomaiWatchNotificationCallback?,_ context: UnsafeMutableRawPointer?)->MikomaiResult { invoke("mikomai_watch_start",[storage_path.map { String(cString:$0) } ?? ""],CompatListener(nil,notification_callback,context)) }
public func mikomai_watch_stop()->MikomaiResult { invoke("mikomai_watch_stop",[],nil) }
public func mikomai_watch_list()->MikomaiResult { invoke("mikomai_watch_list",[],nil) }
public func mikomai_watch_create(_ request_json: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_watch_create",[request_json.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_watch_update(_ id: UnsafePointer<CChar>?,_ request_json: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_watch_update",[id.map { String(cString:$0) } ?? "",request_json.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_watch_enable(_ id: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_watch_enable",[id.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_watch_disable(_ id: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_watch_disable",[id.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_watch_delete(_ id: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_watch_delete",[id.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_watch_run_now(_ id: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_watch_run_now",[id.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_chat(_ message: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_chat",[message.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_chat_with_paths(_ message: UnsafePointer<CChar>?,_ documents_dir: UnsafePointer<CChar>?,_ knowledge_dir: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_chat_with_paths",[message.map { String(cString:$0) } ?? "",documents_dir.map { String(cString:$0) } ?? "",knowledge_dir.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_model_load(_ path: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_model_load",[path.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_model_status()->MikomaiResult { invoke("mikomai_model_status",[],nil) }
public func mikomai_model_select_backend(_ name: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_model_select_backend",[name.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_model_cancel()->MikomaiResult { invoke("mikomai_model_cancel",[],nil) }
public func mikomai_configure_vision(_ enabled: Int32,_ projector_path: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_configure_vision",[String(enabled),projector_path.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_device_registry_read(_ path: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_device_registry_read",[path.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_assistant_chat(_ message: UnsafePointer<CChar>?,_ history: UnsafePointer<CChar>?,_ documents_dir: UnsafePointer<CChar>?,_ knowledge_dir: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_assistant_chat",[message.map { String(cString:$0) } ?? "",history.map { String(cString:$0) } ?? "",documents_dir.map { String(cString:$0) } ?? "",knowledge_dir.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_assistant_chat_with_attachments(_ message: UnsafePointer<CChar>?,_ history: UnsafePointer<CChar>?,_ documents_dir: UnsafePointer<CChar>?,_ knowledge_dir: UnsafePointer<CChar>?,_ attachments: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_assistant_chat_with_attachments",[message.map { String(cString:$0) } ?? "",history.map { String(cString:$0) } ?? "",documents_dir.map { String(cString:$0) } ?? "",knowledge_dir.map { String(cString:$0) } ?? "",attachments.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_assistant_chat_streaming(_ message: UnsafePointer<CChar>?,_ history: UnsafePointer<CChar>?,_ documents_dir: UnsafePointer<CChar>?,_ knowledge_dir: UnsafePointer<CChar>?,_ attachments: UnsafePointer<CChar>?,_ callback: MikomaiStreamCallback?,_ context: UnsafeMutableRawPointer?)->MikomaiResult { invoke("mikomai_assistant_chat_streaming",[message.map { String(cString:$0) } ?? "",history.map { String(cString:$0) } ?? "",documents_dir.map { String(cString:$0) } ?? "",knowledge_dir.map { String(cString:$0) } ?? "",attachments.map { String(cString:$0) } ?? ""],CompatListener(callback,nil,context)) }
public func mikomai_test_tcp_connection(_ host: UnsafePointer<CChar>?,_ port: UInt16,_ timeout_ms: UInt32)->MikomaiResult { invoke("mikomai_test_tcp_connection",[host.map { String(cString:$0) } ?? "",String(port),String(timeout_ms)],nil) }
public func mikomai_set_inference_params(_ temperature: Float,_ repetition_penalty: Float,_ n_ctx: UInt32,_ max_new_tokens: UInt32)->MikomaiResult { invoke("mikomai_set_inference_params",[String(temperature),String(repetition_penalty),String(n_ctx),String(max_new_tokens)],nil) }
public func mikomai_operation_plan_create(_ target: UnsafePointer<CChar>?,_ target_snapshot_json: UnsafePointer<CChar>?,_ commands_json: UnsafePointer<CChar>?,_ rationale: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_operation_plan_create",[target.map { String(cString:$0) } ?? "",target_snapshot_json.map { String(cString:$0) } ?? "",commands_json.map { String(cString:$0) } ?? "",rationale.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_operation_plan_create_generic(_ target: UnsafePointer<CChar>?,_ tool_id: UnsafePointer<CChar>?,_ target_snapshot_json: UnsafePointer<CChar>?,_ args_json: UnsafePointer<CChar>?,_ rationale: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_operation_plan_create_generic",[target.map { String(cString:$0) } ?? "",tool_id.map { String(cString:$0) } ?? "",target_snapshot_json.map { String(cString:$0) } ?? "",args_json.map { String(cString:$0) } ?? "",rationale.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_operation_plan_approve(_ id: UnsafePointer<CChar>?,_ plan_hash: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_operation_plan_approve",[id.map { String(cString:$0) } ?? "",plan_hash.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_operation_plan_get(_ id: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_operation_plan_get",[id.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_operation_audit_list()->MikomaiResult { invoke("mikomai_operation_audit_list",[],nil) }
public func mikomai_operation_plan_begin(_ id: UnsafePointer<CChar>?,_ plan_hash: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_operation_plan_begin",[id.map { String(cString:$0) } ?? "",plan_hash.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_operation_plan_finish(_ id: UnsafePointer<CChar>?,_ succeeded: Int32)->MikomaiResult { invoke("mikomai_operation_plan_finish",[id.map { String(cString:$0) } ?? "",String(succeeded)],nil) }
public func mikomai_operation_execute_approved(_ id: UnsafePointer<CChar>?,_ plan_hash: UnsafePointer<CChar>?,_ credentials_json: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_operation_execute_approved",[id.map { String(cString:$0) } ?? "",plan_hash.map { String(cString:$0) } ?? "",credentials_json.map { String(cString:$0) } ?? ""],nil) }
public func mikomai_native_query(_ request: UnsafePointer<CChar>?)->MikomaiResult { invoke("mikomai_native_query",[request.map { String(cString:$0) } ?? ""],nil) }